- name: Fail when DNS record differs from Pocket host IP
  ansible.builtin.fail:
    msg: |
      DNS record of {{ pocket_host }} does not match host IP address {{ ansible_default_ipv4.address }}
      DNS record: {{ pocket_host_ipv4 | join(', ') }}
  vars:
    pocket_host_ipv4: "{{ lookup('community.general.dig', pocket_host, '@' ~ dns_servers | join(','), wantlist=True) }}"
  when: "ansible_default_ipv4.address not in pocket_host_ipv4"
