- name: Check Pocket node is publicly available
  ansible.builtin.uri:
    url: https://{{ pocket_host }}/v1/query/height
    method: POST
  become: no
  delegate_to: 127.0.0.1

- name: Check genesis.json file
  block:
    - name: Get stats for genesis.json
      ansible.builtin.stat:
        path: "{{ pocket_genesis_path }}"
        checksum_algorithm: sha512
      register: genesis

    - name: Fail when genesis.json not found
      ansible.builtin.fail:
        msg: "Genesis file not found: {{ pocket_genesis_path }}"
      when: not genesis.stat.exists

    - name: Fail when genesis.json checksum is wrong
      ansible.builtin.fail:
        msg: genesis.json has wrong checksum
      when: genesis.stat.checksum != '68c45bc5003c0996fece4dacc39eb2e31f92c8fa3ad1ca905d40ba4ecfea4ee200d3862eb674a07122f6ab716dc1a69679bf8f276a6239a87eb0e4975b2ab007'
  vars:
    pocket_genesis_path: "{{ pocket_home }}/.pocket/config/genesis.json"

- name: Request current Pocket block height
  ansible.builtin.uri:
    url: http://127.0.0.1:{{ pocket_rpc_port }}/v1/query/height
    method: POST
    body_format: json
  register: current_height_response

- name: Request public Pocket block height
  ansible.builtin.uri:
    url: https://supply.research.pokt.network:8192/height
    return_content: true
  register: public_height_response

- name: Fail when Pocket node is not fully synced
  ansible.builtin.fail:
    msg: "Pocket node is not fully synced. Current height: {{ current_height }}, public height: {{ public_height }}"
  vars:
    current_height: "{{ current_height_response.json.height }}"
    public_height: "{{ public_height_response.content }}"
  when: (current_height | int) not in range((public_height | int) - 1, (public_height | int) + 2)

- name: Read Pocket chains file
  ansible.builtin.slurp:
    src: "{{ pocket_home }}/.pocket/config/chains.json"
  register: chains

- include_tasks: request.yaml
  loop: "{{ chains['content'] | b64decode | from_json | map(attribute='id') }}"
  loop_control:
    label: "{{ item }}"
